site: Kristina Leilani Black, PhD

url: https://kristinaleilani.github.io/
baseurl: 

description: "Population genomics applied to wildlife conservation"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /Blog/:slug
  projects:
    output: true
    permalink: /project/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 6
paginate_path: "/Blog/page:num/"
  
